services:
  spring-boot-server:
    container_name: spring-boot-server
    build: .
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
      cache-server:
        condition: service_healthy

  database:
    container_name: mysql-server
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizly
    ports:
      - 3306:3306
    volumes:
      - ./data_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 20

  cache-server:
    container_name: redis-server
    image: redis
    ports:
      - 6379:6379

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 20